import Head from 'next/head';
import React from 'react';
import {Inter } from 'next/font/google';
import { HomePage } from '@/src/components/home/home-page';



const inter = Inter({ subsets: ['latin'] })

//From 'home-page.jsx file' pass 'data' through 'HomePage' component tags

//This will render info in browser now
export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <HomePage data={data} />
       </div>

     );
};

//data property constructred in getServerSideProps is ran through both "HomPage" tag above and component in "home-page.jsx"
export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');
  console.log({ events_categories });
  return {
    props: {
      data: events_categories,
    },
  };

}

      
      
      

   






















